version: 2
updates:
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend
    commit-message:
      prefix: "chore(backend)"

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: "chore(frontend)"
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: "/contracts"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - contracts
    commit-message:
      prefix: "chore(contracts)"
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: "/scripts/cli"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - infra
    commit-message:
      prefix: "chore(infra)"
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - infra
    commit-message:
      prefix: "chore(infra)"
