import {
    WalletContractV3R1,
    WalletContractV3R2,
    WalletContractV4,
    WalletContractV5R1,
} from '@ton/ton';
import { beginCell, Cell, storeStateInit } from '@ton/core';
import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';

// Code cell hash is independent of the public key, so any 32-byte key works.
const publicKey = Buffer.from(
    '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff',
    'hex',
);

// Mirror of Java WalletStateInitParser.extractPublicKeyFromData offsets.
function extractKeyJavaWay(data: Cell, version: string): string {
    const ds = data.beginParse();
    if (version === 'v5r1') {
        ds.loadBit();
        ds.loadUint(32);
        ds.loadUint(32);
    } else {
        ds.loadUint(32);
        ds.loadUint(32);
    }
    return ds.loadBuffer(32).toString('hex');
}

const wallets: Array<{ label: string; init: { code: Cell; data: Cell } }> = [
    { label: 'v3r1', init: WalletContractV3R1.create({ workchain: 0, publicKey }).init },
    { label: 'v3r2', init: WalletContractV3R2.create({ workchain: 0, publicKey }).init },
    { label: 'v4r2', init: WalletContractV4.create({ workchain: 0, publicKey }).init },
    { label: 'v5r1', init: WalletContractV5R1.create({ workchain: 0, publicKey }).init },
];

const javaConstants: Record<string, string> = {
    v3r2: '84dafa449f98a6987789ba232358072bc0f76dc4524002a5d0918b9a75d2d599',
    v4r1: '64dd54805522c5be8a9db59ceb0351bdf9d5cd72f8a3a3094c1a3a0d29a7e2c8',
    v4r2: 'feb5ff6820e2ff0d9483e7e0d62c817d846789fb4ae580c878866d959dabd5c0',
    v5: '20834b7b72b2845e15b13a0eebd2c8810b54c1bb4068a3a4dc5ba2ffe57c19c8',
};

console.log(`Known publicKey: ${publicKey.toString('hex')}`);
console.log('\n=== Real wallet code-cell hashes + key extraction (Java offsets) ===');
for (const w of wallets) {
    const hex = w.init.code.hash().toString('hex');
    let extracted = 'n/a';
    let ok = '';
    if (w.label !== 'v3r1') {
        extracted = extractKeyJavaWay(w.init.data, w.label === 'v5r1' ? 'v5r1' : 'v3v4');
        ok = extracted === publicKey.toString('hex') ? 'KEY-OK' : 'KEY-MISMATCH';
    }
    console.log(`${w.label.padEnd(6)} code=${hex}  extract=${ok}`);
}

console.log('\n=== StateInit BoC fixtures for Java test (v4r2, v5r1) ===');
const props: string[] = [
    '# Generated by contracts/scripts/diag/walletCodeHashes.ts. Do not edit by hand.',
    `publicKey=${publicKey.toString('hex')}`,
];
for (const w of wallets) {
    if (w.label !== 'v4r2' && w.label !== 'v5r1') continue;
    const stateInitCell = beginCell().store(storeStateInit(w.init)).endCell();
    const boc = stateInitCell.toBoc().toString('base64');
    const hashHex = stateInitCell.hash().toString('hex');
    console.log(`--- ${w.label} ---`);
    console.log(`stateInitBoc(base64): ${boc}`);
    console.log(`addressHashPart(hex): ${hashHex}`);
    props.push(`${w.label}.stateInitBoc=${boc}`);
    props.push(`${w.label}.addressHash=${hashHex}`);
}

const outPath = resolve(
    __dirname,
    '../../../backend/src/test/resources/ton/wallet-state-init-fixtures.properties',
);
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, props.join('\n') + '\n', 'utf8');
console.log(`\nWrote fixtures: ${outPath}`);

console.log('\n=== Java WalletStateInitParser constants ===');
for (const [k, v] of Object.entries(javaConstants)) {
    console.log(`${k.padEnd(6)} ${v}`);
}
